LetterAnimations = {
 {'a bold','a'},
 {'b bold','b'},
 {'c bold','c'},
 {'d bold','d'},
 {'e bold','e'},
 {'f bold','f'},
 {'g bold','g'},
 {'h bold','h'},
 {'i bold','i'},
 {'j bold','j'},
 {'k bold','k'},
 {'l bold','l'},
 {'m bold','m'},
 {'n bold','n'},
 {'o bold','o'},
 {'p bold','p'},
 {'q bold','q'},
 {'r bold','r'},
 {'s bold','s'},
 {'t bold','t'},
 {'u bold','u'},
 {'v bold','v'},
 {'w bold','w'},
 {'x bold','x'},
 {'y bold','y'},
 {'z bold','z'},
}