LetterAnimations = {
 {'a bold','a'},
 {'b bold','b'},
 {'c bold','c'},
 {'d bold','d'},
 {'e bold','e'},
 {'f bold','f'},
 {'g bold','g'},
 {'h bold','h'},
 {'i bold','i'},
 {'j bold','j'},
 {'k bold','k'},
 {'l bold','l'},
 {'m bold','m'},
 {'n bold','n'},
 {'o bold','o'},
 {'p bold','p'},
 {'q bold','q'},
 {'r bold','r'},
 {'s bold','s'},
 {'t bold','t'},
 {'u bold','u'},
 {'v bold','v'},
 {'w bold','w'},
 {'x bold','x'},
 {'y bold','y'},
 {'z bold','z'},
 {'0 bold','0'},
 {'1 bold','1'},
 {'2 bold','2'},
 {'3 bold','3'},
 {'4 bold','4'},
 {'5 bold','5'},
 {'6 bold','6'},
 {'7 bold','7'},
 {'8 bold','8'},
 {'9 bold','9'},
 {'+ bold','+'},
 {'- bold','-'},
 {'comma bold',','},
 {'period bold', '.'},

 {'* bold','*'},
}